In [1]:
import pandas as pd
import numpy as np

df_samples = pd.read_csv("/Users/delser/ownCloud/Writing/MetSoc2022_CASMI_results.txt",index_col= "Compound Number", sep="\t") # mzmine quant table

df_pred = pd.read_csv('/Users/delser/ownCloud/mass2smiles_paper/predicted_results_misunderstood-fire-207.tsv',sep="\t") # MS2LDA download

df_ref = pd.read_csv('/Users/delser/mass2smiles/retrain/nist/tcn_seq/casmi_func_groups_2201_mf.tsv',sep="\t")

In [32]:
import pandas as pd
import numpy as np

#df_samples = pd.read_csv("/Users/delser/ownCloud/Writing/MetSoc2022_CASMI_results.txt",index_col= "Compound Number", sep="\t") # mzmine quant table

df_pred = pd.read_csv('/Users/delser/mass2smiles/retrain/nist/tcn_seq/09022023_val_result_5l_50ep_zany-jazz-196.tsv',sep="\t") # MS2LDA download

df_ref = pd.read_csv('/Users/delser/mass2smiles/retrain/nist/tcn_seq/all_HRMS_valid_24012023_cddd_refine_s_mf.tsv',sep="\t")

In [2]:
df_pred

,Unnamed: 0,feature_id,precursor_mz,0,#num_of_sugars,#Number of aliphatic carboxylic acids,#Number of aliphatic hydroxyl groups,#Number of aliphatic hydroxyl groups excluding tert-OH,#Number of N functional groups attached to aromatics,#Number of Aromatic carboxylic acides,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
0,0,398,235.1691,C=C(C)C1CCC2(C)C=CC(=O)C(C)=C2C1,0,0,0,0,0,0,...,15,21,2,0,0,0,0,0,0,0
1,1,398,235.1691,C=C(C)C1CCC2(C)C=CC(=O)C(C)=C2C1,0,0,0,0,0,0,...,15,21,2,0,0,0,0,0,0,0
2,2,159,485.2164,COC1=C(C)c2c(cc3c(c2O)C(=O)OC2(C)C=C(C)C(=O)CC...,0,0,1,1,0,0,...,25,33,7,0,0,0,0,0,0,0
3,3,169,705.2381,COC1=CC(COC(=O)C2OC(OC(C)=O)C(O)C(OC(=O)c3cccc...,1,0,3,2,0,0,...,25,29,13,1,0,0,0,0,0,0
4,4,423,441.2264,CCCCCCCCC(=O)c1cc(CCCC(=O)O)cc(OC(=O)CCC)c1OCOC,0,1,0,0,0,0,...,24,33,7,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,231,439,336.0647,CN1C(=O)CC(S(=O)c2ccccc2)C2=Nc3ccccc3C21,0,0,0,0,0,0,...,17,17,4,2,0,0,0,0,0,0
232,232,322,532.3113,CC1CCC(OC2OC(CO)C(O)C(O)C2O)C2CCC(C)(OC3OC(CO)...,1,0,6,5,0,0,...,29,48,9,0,0,0,0,0,0,0
233,233,300,478.3159,CC(C)=C(C)c1c(O)cc(C)c(C(=O)C2CC(C)(C)c3c(O)cc...,0,0,1,1,0,0,...,27,31,7,0,0,0,0,0,0,0
234,234,254,329.2320,CC(=O)OC(C)CCC1C(C)CCC(OC(=O)C(C)C)C1CC(=O)O,0,1,1,0,0,0,...,20,34,5,0,0,0,0,0,0,0
235,235,237,278.1172,Cc1ccc(C(=O)Nc2ccccc2)c2cccc(O)c12,0,0,0,0,0,0,...,17,16,2,2,0,0,0,0,0,0

In [3]:
df_ref

,Unnamed: 0.1,Unnamed: 0,spectrum_id,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,smiles_preprocessed,num_of_sugars,...,C,H,O,N,S,I,Br,Cl,F,P
0,0,0,3,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,...,35,42,16,0,0,0,0,0,0,0
1,1,1,5,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,...,26,36,8,0,0,0,0,0,0,0
2,2,2,6,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,...,54,84,22,0,0,0,0,0,0,0
3,3,3,10,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,...,25,25,3,7,0,0,0,0,0,0
4,4,4,11,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,...,33,44,10,4,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,237,237,490,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,...,14,21,4,1,0,0,0,0,0,0
238,238,238,491,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,...,28,42,2,0,0,0,0,0,0,0
239,239,239,492,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,...,21,32,8,0,0,0,0,0,0,0
240,240,240,495,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,...,24,32,15,0,0,0,0,0,0,0
241,241,241,500,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,...,15,14,3,0,0,0,0,0,0,0

df_pred['casmi_ID']=df_ref["spectrum_id"]
df_pred

df_pred=df_pred.set_index('casmi_ID')
df_pred

In [4]:
df_pred=df_pred.rename(columns={"0": "predicted"})

df_ref=df_ref.set_index('spectrum_id')

df_samples=df_samples.rename(columns={"SMILES": "CASMI_true"})
df_samples

In [5]:

df_pred=df_pred.drop(["Unnamed: 0"], axis=1)
df_pred

,feature_id,precursor_mz,predicted,#num_of_sugars,#Number of aliphatic carboxylic acids,#Number of aliphatic hydroxyl groups,#Number of aliphatic hydroxyl groups excluding tert-OH,#Number of N functional groups attached to aromatics,#Number of Aromatic carboxylic acides,#Number of aromatic nitrogens,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
0,398,235.1691,C=C(C)C1CCC2(C)C=CC(=O)C(C)=C2C1,0,0,0,0,0,0,0,...,15,21,2,0,0,0,0,0,0,0
1,398,235.1691,C=C(C)C1CCC2(C)C=CC(=O)C(C)=C2C1,0,0,0,0,0,0,0,...,15,21,2,0,0,0,0,0,0,0
2,159,485.2164,COC1=C(C)c2c(cc3c(c2O)C(=O)OC2(C)C=C(C)C(=O)CC...,0,0,1,1,0,0,0,...,25,33,7,0,0,0,0,0,0,0
3,169,705.2381,COC1=CC(COC(=O)C2OC(OC(C)=O)C(O)C(OC(=O)c3cccc...,1,0,3,2,0,0,0,...,25,29,13,1,0,0,0,0,0,0
4,423,441.2264,CCCCCCCCC(=O)c1cc(CCCC(=O)O)cc(OC(=O)CCC)c1OCOC,0,1,0,0,0,0,0,...,24,33,7,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,439,336.0647,CN1C(=O)CC(S(=O)c2ccccc2)C2=Nc3ccccc3C21,0,0,0,0,0,0,0,...,17,17,4,2,0,0,0,0,0,0
232,322,532.3113,CC1CCC(OC2OC(CO)C(O)C(O)C2O)C2CCC(C)(OC3OC(CO)...,1,0,6,5,0,0,0,...,29,48,9,0,0,0,0,0,0,0
233,300,478.3159,CC(C)=C(C)c1c(O)cc(C)c(C(=O)C2CC(C)(C)c3c(O)cc...,0,0,1,1,0,0,0,...,27,31,7,0,0,0,0,0,0,0
234,254,329.2320,CC(=O)OC(C)CCC1C(C)CCC(OC(=O)C(C)C)C1CC(=O)O,0,1,1,0,0,0,0,...,20,34,5,0,0,0,0,0,0,0
235,237,278.1172,Cc1ccc(C(=O)Nc2ccccc2)c2cccc(O)c12,0,0,0,0,0,0,1,...,17,16,2,2,0,0,0,0,0,0

In [6]:
df_pred=df_pred.drop(["precursor_mz"], axis=1)
df_pred

,feature_id,predicted,#num_of_sugars,#Number of aliphatic carboxylic acids,#Number of aliphatic hydroxyl groups,#Number of aliphatic hydroxyl groups excluding tert-OH,#Number of N functional groups attached to aromatics,#Number of Aromatic carboxylic acides,#Number of aromatic nitrogens,#Number of aromatic amines,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
0,398,C=C(C)C1CCC2(C)C=CC(=O)C(C)=C2C1,0,0,0,0,0,0,0,0,...,15,21,2,0,0,0,0,0,0,0
1,398,C=C(C)C1CCC2(C)C=CC(=O)C(C)=C2C1,0,0,0,0,0,0,0,0,...,15,21,2,0,0,0,0,0,0,0
2,159,COC1=C(C)c2c(cc3c(c2O)C(=O)OC2(C)C=C(C)C(=O)CC...,0,0,1,1,0,0,0,0,...,25,33,7,0,0,0,0,0,0,0
3,169,COC1=CC(COC(=O)C2OC(OC(C)=O)C(O)C(OC(=O)c3cccc...,1,0,3,2,0,0,0,0,...,25,29,13,1,0,0,0,0,0,0
4,423,CCCCCCCCC(=O)c1cc(CCCC(=O)O)cc(OC(=O)CCC)c1OCOC,0,1,0,0,0,0,0,0,...,24,33,7,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,439,CN1C(=O)CC(S(=O)c2ccccc2)C2=Nc3ccccc3C21,0,0,0,0,0,0,0,0,...,17,17,4,2,0,0,0,0,0,0
232,322,CC1CCC(OC2OC(CO)C(O)C(O)C2O)C2CCC(C)(OC3OC(CO)...,1,0,6,5,0,0,0,0,...,29,48,9,0,0,0,0,0,0,0
233,300,CC(C)=C(C)c1c(O)cc(C)c(C(=O)C2CC(C)(C)c3c(O)cc...,0,0,1,1,0,0,0,0,...,27,31,7,0,0,0,0,0,0,0
234,254,CC(=O)OC(C)CCC1C(C)CCC(OC(=O)C(C)C)C1CC(=O)O,0,1,1,0,0,0,0,0,...,20,34,5,0,0,0,0,0,0,0
235,237,Cc1ccc(C(=O)Nc2ccccc2)c2cccc(O)c12,0,0,0,0,0,0,1,0,...,17,16,2,2,0,0,0,0,0,0

In [7]:
df_ref=df_ref.set_index('spectrum_id')
df_pred=df_pred.set_index('feature_id')

In [8]:
df_ref

,Unnamed: 0.1,Unnamed: 0,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,smiles_preprocessed,num_of_sugars,Number of aliphatic carboxylic acids,...,C,H,O,N,S,I,Br,Cl,F,P
spectrum_id,,,,,,,,,,,,,,,,,,,,,
3,0,0,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,...,35,42,16,0,0,0,0,0,0,0
5,1,1,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,...,26,36,8,0,0,0,0,0,0,0
6,2,2,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,...,54,84,22,0,0,0,0,0,0,0
10,3,3,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,...,25,25,3,7,0,0,0,0,0,0
11,4,4,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,...,33,44,10,4,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,237,237,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,...,14,21,4,1,0,0,0,0,0,0
491,238,238,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,...,28,42,2,0,0,0,0,0,0,0
492,239,239,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,...,21,32,8,0,0,0,0,0,0,0
495,240,240,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,...,24,32,15,0,0,0,0,0,0,0
500,241,241,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,...,15,14,3,0,0,0,0,0,0,0

In [9]:
df_ref = df_ref[~df_ref.index.duplicated(keep='first')]

In [10]:
df_ref

,Unnamed: 0.1,Unnamed: 0,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,smiles_preprocessed,num_of_sugars,Number of aliphatic carboxylic acids,...,C,H,O,N,S,I,Br,Cl,F,P
spectrum_id,,,,,,,,,,,,,,,,,,,,,
3,0,0,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,...,35,42,16,0,0,0,0,0,0,0
5,1,1,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,...,26,36,8,0,0,0,0,0,0,0
6,2,2,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,...,54,84,22,0,0,0,0,0,0,0
10,3,3,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,...,25,25,3,7,0,0,0,0,0,0
11,4,4,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,...,33,44,10,4,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,237,237,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,...,14,21,4,1,0,0,0,0,0,0
491,238,238,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,...,28,42,2,0,0,0,0,0,0,0
492,239,239,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,...,21,32,8,0,0,0,0,0,0,0
495,240,240,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,...,24,32,15,0,0,0,0,0,0,0
500,241,241,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,...,15,14,3,0,0,0,0,0,0,0

In [11]:
df_final = df_ref.join(df_pred, how="outer")
#df_final=df_final.drop(["Column 3"], axis=1)
#df_final=df_final.drop(["Adduct","spec","smiles"], axis=1)
df_final

,Unnamed: 0.1,Unnamed: 0,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,smiles_preprocessed,num_of_sugars,Number of aliphatic carboxylic acids,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
3,0,0,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,...,23,29,14,0,0,0,0,0,0,0
5,1,1,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,...,28,38,8,0,0,0,0,0,0,0
6,2,2,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,...,29,46,9,0,0,0,0,0,0,0
10,3,3,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,...,28,28,4,5,0,0,0,0,0,0
11,4,4,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,...,30,46,8,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,237,237,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,...,14,23,5,1,0,0,0,0,0,0
491,238,238,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,...,30,48,3,0,0,0,0,0,0,0
492,239,239,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,...,21,33,8,0,0,0,0,0,0,0
495,240,240,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,...,21,30,14,0,0,0,0,0,0,0
500,241,241,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,...,15,13,2,0,0,0,0,0,0,0

In [12]:
df_final=df_final.rename(columns={"smiles_preprocessed": "CASMI_true"})
df_final

,Unnamed: 0.1,Unnamed: 0,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,CASMI_true,num_of_sugars,Number of aliphatic carboxylic acids,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
3,0,0,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,...,23,29,14,0,0,0,0,0,0,0
5,1,1,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,...,28,38,8,0,0,0,0,0,0,0
6,2,2,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,...,29,46,9,0,0,0,0,0,0,0
10,3,3,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,...,28,28,4,5,0,0,0,0,0,0
11,4,4,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,...,30,46,8,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,237,237,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,...,14,23,5,1,0,0,0,0,0,0
491,238,238,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,...,30,48,3,0,0,0,0,0,0,0
492,239,239,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,...,21,33,8,0,0,0,0,0,0,0
495,240,240,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,...,21,30,14,0,0,0,0,0,0,0
500,241,241,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,...,15,13,2,0,0,0,0,0,0,0

In [13]:
df_final=df_final.rename(columns={"smiles_preprocessed": "val_true"})
df_final

,Unnamed: 0.1,Unnamed: 0,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,CASMI_true,num_of_sugars,Number of aliphatic carboxylic acids,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
3,0,0,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,...,23,29,14,0,0,0,0,0,0,0
5,1,1,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,...,28,38,8,0,0,0,0,0,0,0
6,2,2,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,...,29,46,9,0,0,0,0,0,0,0
10,3,3,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,...,28,28,4,5,0,0,0,0,0,0
11,4,4,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,...,30,46,8,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,237,237,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,...,14,23,5,1,0,0,0,0,0,0
491,238,238,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,...,30,48,3,0,0,0,0,0,0,0
492,239,239,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,...,21,33,8,0,0,0,0,0,0,0
495,240,240,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,...,21,30,14,0,0,0,0,0,0,0
500,241,241,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,...,15,13,2,0,0,0,0,0,0,0

In [14]:

df_final=df_final.drop(["Unnamed: 0"], axis=1)
df_final

,Unnamed: 0.1,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,CASMI_true,num_of_sugars,Number of aliphatic carboxylic acids,Number of aliphatic hydroxyl groups,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
3,0,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,5,...,23,29,14,0,0,0,0,0,0,0
5,1,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,1,...,28,38,8,0,0,0,0,0,0,0
6,2,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,11,...,29,46,9,0,0,0,0,0,0,0
10,3,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,0,...,28,28,4,5,0,0,0,0,0,0
11,4,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,0,...,30,46,8,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,237,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,0,...,14,23,5,1,0,0,0,0,0,0
491,238,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,1,...,30,48,3,0,0,0,0,0,0,0
492,239,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,4,...,21,33,8,0,0,0,0,0,0,0
495,240,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,7,...,21,30,14,0,0,0,0,0,0,0
500,241,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,0,...,15,13,2,0,0,0,0,0,0,0

In [15]:

df_final=df_final.drop(["Unnamed: 0.1"], axis=1)
df_final

,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,CASMI_true,num_of_sugars,Number of aliphatic carboxylic acids,Number of aliphatic hydroxyl groups,Number of aliphatic hydroxyl groups excluding tert-OH,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
3,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,5,5,...,23,29,14,0,0,0,0,0,0,0
5,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,1,1,...,28,38,8,0,0,0,0,0,0,0
6,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,11,11,...,29,46,9,0,0,0,0,0,0,0
10,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,0,0,...,28,28,4,5,0,0,0,0,0,0
11,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,0,0,...,30,46,8,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,0,0,...,14,23,5,1,0,0,0,0,0,0
491,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,1,1,...,30,48,3,0,0,0,0,0,0,0
492,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,4,4,...,21,33,8,0,0,0,0,0,0,0
495,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,7,7,...,21,30,14,0,0,0,0,0,0,0
500,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,0,0,...,15,13,2,0,0,0,0,0,0,0

df_final=df_final.drop(["Unnamed: 0.1"], axis=1)
df_final

In [9]:
df_final["CASMI_true"][1]

'CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=O)CCC(=O)O)C)OC(=O)C'

In [10]:
df_final["predicted"][1]

'CC(C=CC1(O)CCC(=O)C=C1C)=CC=CC(C)C1OC(CC(=O)O)CCC1C'

In [9]:
from rdkit import DataStructs
from rdkit import Chem
#m_true=Chem.MolFromSmiles(df_final["decoded_test"][1])
#m_predict=Chem.MolFromSmiles(df_final["predicted"][1])
#ms=[m_true,m_predict]
#fps = [Chem.RDKFingerprint(x) for x in ms]
#DataStructs.FingerprintSimilarity(fps[0],fps[1])


def get_tani(smiles1,smiles2):
    try:
        m_true=Chem.MolFromSmiles(smiles1,sanitize=False)
        m_predict=Chem.MolFromSmiles(smiles2,sanitize=False)
        ms=[m_true,m_predict]
        fps = [Chem.RDKFingerprint(x) for x in ms]
        return DataStructs.FingerprintSimilarity(fps[0],fps[1])
    except:
        return "no_prediction_or_error_with_parsing_by_rdkit"

In [16]:
from rdkit import DataStructs
from rdkit import Chem
#m_true=Chem.MolFromSmiles(df_final["decoded_test"][1])
#m_predict=Chem.MolFromSmiles(df_final["predicted"][1])
#ms=[m_true,m_predict]
#fps = [Chem.RDKFingerprint(x) for x in ms]
#DataStructs.FingerprintSimilarity(fps[0],fps[1])


def get_tani(smiles1,smiles2):
    try:
        m_true=Chem.MolFromSmiles(smiles1,)
        m_predict=Chem.MolFromSmiles(smiles2)
        ms=[m_true,m_predict]
        fps = [Chem.RDKFingerprint(x) for x in ms]
        return DataStructs.FingerprintSimilarity(fps[0],fps[1])
    except:
        return "no_prediction_or_error_with_parsing_by_rdkit"

In [17]:
df_final['tanimoto'] = df_final.apply(lambda x: get_tani(x.CASMI_true, x.predicted), axis=1)
#df_final['tanimoto'] = df_final.apply(lambda x: get_tani(x.val_true, x.predicted), axis=1)

In [18]:
df_final

,precursor_mz,mzs,intensities,loss_mzs,loss_intensities,CASMI_true,num_of_sugars,Number of aliphatic carboxylic acids,Number of aliphatic hydroxyl groups,Number of aliphatic hydroxyl groups excluding tert-OH,...,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P,tanimoto
3,719.2538,"[53.0387, 55.0179, 55.0545, 57.0338, 59.0492, ...","[0.017272727272727273, 0.01818181818181818, 0....",[314.15709999999996],[0.01818181818181818],CC1C(C(C(C(O1)OC2=C(OC3=C(C(=CC(=C3C2=O)O)O)CC...,2.0,0,5,5,...,29,14,0,0,0,0,0,0,0,0.476653
5,499.2298,"[67.0543, 69.0698, 81.0699, 83.0492, 83.0853, ...","[0.010357142857142856, 0.04642857142857143, 0....","[60.02260000000001, 118.02660000000003, 160.03...","[0.060714285714285714, 0.39285714285714285, 0....",CC1CC2(C(C1O)C=C(C(CC3C(C3(C)C)C=C(C2=O)C)OC(=...,0.0,1,1,1,...,38,8,0,0,0,0,0,0,0,0.564030
6,1102.5777,"[81.0334, 83.0491, 85.0224, 85.0284, 85.0333, ...","[0.14210526315789473, 0.2236842105263158, 0.01...",[],[],CC1C(C(C(C(O1)OC2C(OC(C(C2O)O)OCC3C(C(C(C(O3)O...,4.0,0,11,11,...,46,9,0,0,0,0,0,0,0,0.594069
10,472.2082,"[72.2736, 145.0759, 148.0868, 149.0707, 172.06...","[0.010697674418604652, 0.03488372093023256, 0....","[135.07919999999996, 148.0632, 165.08959999999...","[0.053488372093023255, 0.10465116279069768, 0....",CN1C2=C(C=C(C=C2)C(=O)N(CCC(=O)O)C3=CC=CC=N3)N...,0.0,1,0,0,...,28,4,5,0,0,0,0,0,0,0.508880
11,657.3116,"[55.0542, 55.9818, 57.0334, 60.2456, 69.0335, ...","[0.018260869565217393, 0.013043478260869565, 0...","[158.094, 210.1282, 228.1352, 246.1485, 280.16...","[0.02217391304347826, 0.06086956521739131, 0.1...",CCCC(=O)OCC(C(C(CN1C2=C(C=C(C(=C2)C)C)N=C3C1=N...,1.0,0,0,0,...,46,8,0,0,0,0,0,0,0,0.355041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,268.1541,"[86.0599, 109.065, 109.1013, 121.101, 123.1168...","[0.10689655172413794, 0.04482758620689655, 0.0...","[18.01030000000003, 36.02120000000002, 46.0054...","[0.21724137931034482, 0.06206896551724138, 1.0...",CC1CCC2C1C(=O)OC(C2C)NC(=O)C3C(O3)C,0.0,0,0,0,...,23,5,1,0,0,0,0,0,0,0.357607
491,411.3254,"[55.0544, 57.0701, 67.0544, 69.0699, 81.0699, ...","[0.0215625, 0.053125, 0.015, 0.34375, 0.046875...","[18.01060000000001, 88.08850000000001, 142.135...","[0.153125, 0.02125, 0.01875, 0.02625, 0.028437...",CC(C)C(C)C=CC(C)C1CCC2C1(CCC3=C2C(=O)C=C4C3(CC...,0.0,0,1,1,...,48,3,0,0,0,0,0,0,0,0.515651
492,430.2432,"[50.4192, 52.9216, 74.1355, 81.0699, 86.4846, ...","[0.05555555555555555, 0.058333333333333334, 0....","[98.63150000000002, 179.0794, 197.0896, 214.55...","[0.06666666666666667, 0.2777777777777778, 1.0,...",CC1CCC(C2(C1=CC(CC2)C(=C)C(=O)O)C)OC3C(C(C(C(O...,1.0,1,4,4,...,33,8,0,0,0,0,0,0,0,0.487228
495,578.2076,"[54.5814, 57.0338, 61.0286, 69.0335, 81.0331, ...","[0.01, 0.010769230769230769, 0.038461538461538...",[160.76359999999994],[0.011923076923076923],COC1=C2C(=CC(=C1OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(...,2.0,1,7,7,...,30,14,0,0,0,0,0,0,0,0.622912
500,243.1014,"[71.9563, 104.546, 105.0698, 107.0491, 107.056...","[0.015833333333333335, 0.018333333333333333, 0...","[24.813600000000008, 42.197700000000026, 94.04...","[0.025833333333333333, 0.0175, 0.065, 1.0, 0.6...",C1C(COC2=C1C=CC(=C2)O)C3=CC=C(C=C3)O,0.0,0,0,0,...,13,2,0,0,0,0,0,0,0,1.000000

In [13]:
import numpy as np
#x=np.load('allclean050122_predicted.npy')
x=np.load('/Users/delser/mass2smiles/retrain/nist/tcn_seq/casmi_predict1.npy')
#x=np.load('/Users/delser/mass2smiles/retrain/nist/tcn_seq/val_predict1.npy')

In [14]:
def float_oupt_to_class(oupt, k):
  end_pts = np.zeros(k+1, dtype=np.float32) 
  delta = 1.0 / k
  for i in range(k):
    end_pts[i] = i * delta
  end_pts[k] = 1.0
  # if k=4, [0.0, 0.25, 0.50, 0.75, 1.0] 

  for i in range(k):
    if oupt >= end_pts[i] and oupt <= end_pts[i+1]:
      return i
  return -1  # fatal error

In [15]:
funct=['#num_of_sugars',"#Number of aliphatic carboxylic acids",
 "#Number of aliphatic hydroxyl groups",
 "#Number of aliphatic hydroxyl groups excluding tert-OH",
 "#Number of N functional groups attached to aromatics",
 "#Number of Aromatic carboxylic acides",
 "#Number of aromatic nitrogens",
 "#Number of aromatic amines",
 "#Number of aromatic hydroxyl groups",
 "#Number of carboxylic acids",
 "#Number of carboxylic acids",
 "#Number of carbonyl O",
 "#Number of carbonyl O, excluding COOH",
 "#Number of thiocarbonyl",
 "#Number of Imines",
 "#Number of Tertiary amines",
 "#Number of Secondary amines",
 "#Number of Primary amines",
 "#Number of hydroxylamine groups",
 "#Number of tert-alicyclic amines (no heteroatoms, not quinine-like bridged N)",
 "#Number of H-pyrrole nitrogens",
 "#Number of thiol groups",
 "#Number of aldehydes",
 "#Number of alkyl carbamates (subject to hydrolysis)",
 "#Number of alkyl halides",
 "#Number of allylic oxidation sites excluding steroid dienone",
 "#Number of amides",
 "#Number of anilines",
 "#Number of aryl methyl sites for hydroxylation",
 "#Number of azo groups",
 "#Number of benzene rings",
 "#Bicyclic",
 "#Number of dihydropyridines",
 "#Number of epoxide rings",
 "#Number of esters",
 "#Number of ether oxygens (including phenoxy)",
 "#Number of furan rings",
 "#Number of guanidine groups",
 "#Number of halogens",
 "#Number of imidazole rings",
 "#Number of isothiocyanates",
 "#Number of ketones",
 "#Number of ketones excluding diaryl, a,b-unsat. dienones, heteroatom on Calpha",
 "#Number of beta lactams",
 "#Number of cyclic esters (lactones)",
 "#Number of methoxy groups -OCH3",
 "#Number of nitriles",
 "#Number of nitro groups",
 "#Number of oxazole rings",
 "#Number of para-hydroxylation sites",
 "#Number of phenols",
 "#Number of phosphoric acid groups",
 "#Number of phosphoric ester groups",
 "#Number of piperdine rings",
 "#Number of primary amides",
 "#Number of pyridine rings",
 "#Number of quaternary nitrogens",
 "#Number of thioether",
 "#Number of thiazole rings",
 "#Number of unbranched alkanes of at least 4 members (excludes halogenated alkanes)",
      "#adduct_enc","#C","#H", "#O","#N", "#S", "#I", "#Br","#Cl", "#F","#P"]

In [17]:
x[0][0]

0.024481766

In [18]:
float_oupt_to_class(x[0][2], 24)

1

In [16]:
all_arr=[]
for sample in x:
    cache=[]
    for i in sample:
        cache.append(float_oupt_to_class(i,65))
    x=np.array(cache)
    all_arr.append(x)
    
result=np.stack(all_arr)   
result.shape

(242, 71)

In [17]:
df = pd.DataFrame(result, columns = funct)
df

,#num_of_sugars,#Number of aliphatic carboxylic acids,#Number of aliphatic hydroxyl groups,#Number of aliphatic hydroxyl groups excluding tert-OH,#Number of N functional groups attached to aromatics,#Number of Aromatic carboxylic acides,#Number of aromatic nitrogens,#Number of aromatic amines,#Number of aromatic hydroxyl groups,#Number of carboxylic acids,...,#C,#H,#O,#N,#S,#I,#Br,#Cl,#F,#P
0,0,0,1,1,0,0,1,0,0,0,...,11,16,3,3,0,0,0,0,0,0
1,0,0,1,1,0,0,0,0,0,1,...,26,38,6,0,0,0,0,0,0,0
2,0,0,2,2,0,0,0,0,0,0,...,13,20,5,1,0,0,0,0,0,0
3,0,0,0,0,1,0,2,0,0,0,...,11,12,1,3,1,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,15,13,1,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,0,0,0,0,0,0,1,0,0,0,...,14,14,2,2,0,0,0,0,0,0
238,0,0,1,1,0,0,0,0,0,0,...,20,26,2,0,0,0,0,0,0,0
239,0,0,0,0,0,0,0,0,0,0,...,15,18,2,1,0,0,0,0,0,0
240,0,0,0,0,0,0,0,0,0,0,...,11,11,3,1,0,0,0,0,0,0
241,0,0,0,0,0,0,0,0,1,0,...,15,16,2,1,0,0,0,0,0,0

In [19]:
df_final = df_final.join(df, how="outer")
#df_final=df_final.drop(["Column 3"], axis=1)
#df_final=df_final.drop(["Adduct","spec","smiles"], axis=1)
df_final

NameError: name 'df' is not defined

In [12]:
#df_final.to_csv("first-predictions-validation_050122.tsv",sep='\t')
#df_final.to_csv("/Users/delser/ownCloud/Writing/casmi_tanimoto_0707022.tsv",sep='\t')
df_final.to_csv("/Users/delser/mass2smiles/retrain/predicted_results_casmi16082022_tanimoto.tsv",sep='\t')

In [14]:
df_final.to_csv("/Users/delser/ownCloud/mass2smiles_paper/predicted_results_casmi28102022_tanimoto.tsv",sep='\t')

In [15]:
df_final.to_csv("/Users/delser/mass2smiles/retrain/nist/spconv/casmi_result_tanimoto_14112022.tsv",sep='\t')

In [ ]:
'/Users/delser/mass2smiles/retrain/nist/tcn_seq/12122022_casmi_result.tsv'

In [20]:
df_final.to_csv('/Users/delser/mass2smiles/retrain/nist/tcn_seq/casmi_result_5l_50ep_misunderstood-fire-207_tanimoto_mf.tsv',sep='\t')

In [ ]:
09022023_val_result_4l_50ep_twilight-durian-197.tsv